language: php
php:
  - 7
  - 7.1
  - hhvm

sudo: required

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - composer selfupdate
  - composer install --no-interaction

script:
  - ./vendor/bin/phpspec run