language: php
php:
  - 7.1
  - 7.2
  - hhvm

sudo: required

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.2

before_script:
  - composer selfupdate
  - composer install --no-interaction

script:
  - ./vendor/bin/phpspec run --no-interaction